# numpy基础

In [1]:
import numpy as np

In [18]:
array=np.array([[1,2,3],[4,5,6]])    # 二维数组

In [19]:
print(array)

[[1 2 3]
 [4 5 6]]


In [20]:
print('array\'s dimension:',array.ndim)   # ndim 数组的维数

array's dimension: 2


In [21]:
print('array shape:',array.shape)      # shape 数组的形状

array shape: (2, 3)


In [24]:
print(array.size)

6


# numpy创建array

In [25]:
import numpy as np

In [249]:
a=np.array([3,5,6],dtype='int16')   # dtype设置变量类型   一维数组

In [250]:
print(a)

[3 5 6]


In [42]:
print(a.dtype)

int64


In [45]:
a2=np.array([[1,2,34],
           [4,5,6]])       # 两行三列数组（二维数组）

In [59]:
print(a2)

[[ 1  2 34]
 [ 4  5  6]]


In [60]:
a3=np.zeros((3,4),dtype=int)   # 生成3行4列的零矩阵

In [58]:
print(a3)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [68]:
a4=np.arange(10,30,2).reshape((2,5))   # 生成有序数列 并reshape为预设维数

In [66]:
print(a4)

[[10 12 14 16 18]
 [20 22 24 26 28]]


In [79]:
a5=np.linspace(1,10,2,dtype=int).reshape(2,1)   # 生成若干个等分数据

In [80]:
print(a5)

[[ 1]
 [10]]


# numpy的基础运算

In [81]:
import numpy as np

In [82]:
a1=np.array([1,2,34])

In [90]:
a2=np.arange(3)

In [91]:
c1=a1-a2

In [92]:
print(c1)

[ 1  1 32]


In [93]:
c2=a1*a2    # 逐个对应位置元素相乘

In [94]:
print(c2)

[ 0  2 68]


In [97]:
c3=a1**2   #  求平方

In [98]:
print(c3)

[   1    4 1156]


In [99]:
c4=np.sin(a1)   # 弧度制计算三角函数

In [100]:
print(c4)

[0.84147098 0.90929743 0.52908269]


In [102]:
print(a1<4)   # 逻辑运算

[ True  True False]


In [111]:
b=np.array([[1,2],[4,6]])

In [112]:
print(b)

[[1 2]
 [4 6]]


In [115]:
b1=np.arange(4).reshape(2,2)

In [116]:
print(b1)

[[0 1]
 [2 3]]


In [117]:
b3=b*b1     # 对应下标相乘

In [118]:
print(b3)

[[ 0  2]
 [ 8 18]]


In [120]:
b4=np.dot(b,b1)   # 矩阵乘法

In [122]:
print(b4)    #矩阵乘法

[[ 4  7]
 [12 22]]


In [126]:
b5=np.random.random((2,5))    #生成随机数列

In [127]:
print(b5)

[[0.53634667 0.09478571 0.92707953 0.75022293 0.99101283]
 [0.75818665 0.38432052 0.85174827 0.97103758 0.24106626]]


In [128]:
print(np.sum(b5))

6.505806944692968


In [129]:
print(np.max(b5))

0.991012826441555


In [132]:
print(np.min(b5,axis=1))    # 求行的最小值  axis=1表示行，0表示列

[0.09478571 0.24106626]


#  numpy的基础运算2

In [1]:
import numpy as np

In [2]:
a=np.arange(2,14).reshape((3,4))

In [3]:
print(a)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [4]:
np.argmin(a)  # argmin查找最小值的索引

0

In [6]:
np.argmax(a)

11

In [8]:
np.mean(a)     # 求均值

7.5

In [9]:
a.mean()      # 求均值

7.5

In [10]:
np.average(a)   # 求均值

7.5

In [12]:
np.median(a)    # 中位数

7.5

In [13]:
np.cumsum(a)   # 累加

array([ 2,  5,  9, 14, 20, 27, 35, 44, 54, 65, 77, 90], dtype=int32)

In [14]:
np.diff(a)   #每两个相邻元素之差

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [15]:
np.nonzero(a)

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))

In [17]:
a=[[1,2,3],[6,4,6],[8,6,3]]

In [18]:
np.sort(a)    # 逐行排序

array([[1, 2, 3],
       [4, 6, 6],
       [3, 6, 8]])

In [20]:
np.transpose(a)  #转置

array([[1, 6, 8],
       [2, 4, 6],
       [3, 6, 3]])

In [26]:
np.clip(a,2,4)   #设置范围，截断取整

array([[2, 2, 3],
       [4, 4, 4],
       [4, 4, 3]])

In [28]:
np.mean(a,axis=0,dtype=np.int16)   # 对列求均值

array([5, 4, 4], dtype=int16)

# numpy的索引 

In [56]:
import numpy as np

In [57]:
a=np.arange(1,10)

In [58]:
print(a)

[1 2 3 4 5 6 7 8 9]


In [59]:
print(a[1])

2


In [60]:
a=np.arange(1,13).reshape(3,4)

In [61]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [62]:
print(a[0][1])

2


In [63]:

print(a[2,3])

12


In [64]:
print(a[2,:])

[ 9 10 11 12]


In [65]:
a.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [66]:
for row in a.transpose():
    print(row)

[1 5 9]
[ 2  6 10]
[ 3  7 11]
[ 4  8 12]


In [69]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [71]:
for item in a.flat:
    print(item)

1
2
3
4
5
6
7
8
9
10
11
12


# numpy的array合并

In [149]:
import numpy as np

In [150]:
a=np.array([1,1,1])  #行序列

In [151]:
b=np.array([2,2,2])

In [152]:
print(np.vstack((a,b,a)))  #vertical stack

[[1 1 1]
 [2 2 2]
 [1 1 1]]


In [153]:
print(np.hstack((a,b,a)))  #horizontal stack

[1 1 1 2 2 2 1 1 1]


In [154]:
a=a[:,np.newaxis]  #将序列转为数组

In [155]:
b=b[:,np.newaxis]

In [156]:
np.hstack((a,b))

array([[1, 2],
       [1, 2],
       [1, 2]])

In [157]:
c=np.concatenate((a,b,b,a),axis=1)

In [ ]:
print(c)

#  numpy 的array分割

In [2]:
import numpy as np

In [4]:
a=np.arange(12).reshape((3,4))

In [5]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [6]:
print(np.split(a,2,axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [11]:
print(np.split(a,3,axis=0))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [13]:
print(np.array_split(a,2,axis=0))   #不等项分割

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [16]:
print(np.vsplit(a,3))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [17]:
print(np.hsplit(a,2))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


# numpy的copy

In [18]:
import numpy as np

In [19]:
a=np.arange(4)

In [20]:
print(a)

[0 1 2 3]


In [21]:
b=a  #通过赋值的与原型一模一样，改变任何一个，其他的都会被改变

In [22]:
c=a

In [23]:
d=b

In [24]:
a[0]=3

In [25]:
a

array([3, 1, 2, 3])

In [26]:
b

array([3, 1, 2, 3])

In [27]:
b is a

True

In [28]:
c

array([3, 1, 2, 3])

In [29]:
c is a

True

In [30]:
d is a

True

In [31]:
d[1:3]=[22,33]

In [32]:
a

array([ 3, 22, 33,  3])

In [33]:
b=a.copy()   #复制，但没有关联上

In [34]:
b

array([ 3, 22, 33,  3])

In [39]:
b[3]=867

In [40]:
b

array([  3,  22,  33, 867])

In [41]:
a

array([ 3, 22, 33,  3])

In [42]:
a[1:]

array([22, 33,  3])

In [44]:
a[:]

array([ 3, 22, 33,  3])

# pandas基本介绍

In [56]:
import pandas as pd

In [57]:
import numpy as np

In [58]:
s=pd.Series([1,2,4,np.nan,44,2])

In [59]:
s

0     1.0
1     2.0
2     4.0
3     NaN
4    44.0
5     2.0
dtype: float64

In [60]:
dates=pd.date_range('20191001',periods=6)

In [61]:
dates

DatetimeIndex(['2019-10-01', '2019-10-02', '2019-10-03', '2019-10-04',
               '2019-10-05', '2019-10-06'],
              dtype='datetime64[ns]', freq='D')

In [68]:
df=pd.DataFrame(np.random.randn(6,4),index=dates,columns=['a','b','c','d'])  #dataframe建表函数  index columns

In [69]:
df

a         b         c         d
2019-10-01  1.182470  1.097689  1.251941  1.720772
2019-10-02 -0.429110  0.982966 -2.790298 -0.885451
2019-10-03 -1.830451  0.353887 -1.592026  0.304000
2019-10-04  0.453348  0.028451  1.123210  0.807950
2019-10-05 -2.021653 -1.139404  0.576601  0.620634
2019-10-06 -1.243842 -1.760533 -0.620967 -2.392456

In [71]:
df1=pd.DataFrame(np.arange(12).reshape(3,4),index=['一个','两个','三个'],columns=['a','b','c','d'])

In [72]:
df1

a  b   c   d
一个  0  1   2   3
两个  4  5   6   7
三个  8  9  10  11

In [76]:
df2=pd.DataFrame({'A':12,
                 'B':pd.Timestamp('20191001'),
                 'C':pd.Series(1,index=list(range(4)),dtype='float32'),
                 'D':np.array([3]*4,dtype='int32'),
                 'E':pd.Categorical(["test","test","test","test"]),
                 'F':'foo'})    #使用字典创建

In [77]:
df2

A          B    C  D     E    F
0  12 2019-10-01  1.0  3  test  foo
1  12 2019-10-01  1.0  3  test  foo
2  12 2019-10-01  1.0  3  test  foo
3  12 2019-10-01  1.0  3  test  foo

In [80]:
df2.dtypes

A             int64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [81]:
df2.index

Int64Index([0, 1, 2, 3], dtype='int64')

In [82]:
df2.columns

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')

In [83]:
df2.values

array([[12, Timestamp('2019-10-01 00:00:00'), 1.0, 3, 'test', 'foo'],
       [12, Timestamp('2019-10-01 00:00:00'), 1.0, 3, 'test', 'foo'],
       [12, Timestamp('2019-10-01 00:00:00'), 1.0, 3, 'test', 'foo'],
       [12, Timestamp('2019-10-01 00:00:00'), 1.0, 3, 'test', 'foo']],
      dtype=object)

In [84]:
df2.describe()

A    C    D
count   4.0  4.0  4.0
mean   12.0  1.0  3.0
std     0.0  0.0  0.0
min    12.0  1.0  3.0
25%    12.0  1.0  3.0
50%    12.0  1.0  3.0
75%    12.0  1.0  3.0
max    12.0  1.0  3.0

In [85]:
df2.T

0                    1                    2  \
A                   12                   12                   12   
B  2019-10-01 00:00:00  2019-10-01 00:00:00  2019-10-01 00:00:00   
C                    1                    1                    1   
D                    3                    3                    3   
E                 test                 test                 test   
F                  foo                  foo                  foo   

                     3  
A                   12  
B  2019-10-01 00:00:00  
C                    1  
D                    3  
E                 test  
F                  foo

In [86]:
df2.transpose()

0                    1                    2  \
A                   12                   12                   12   
B  2019-10-01 00:00:00  2019-10-01 00:00:00  2019-10-01 00:00:00   
C                    1                    1                    1   
D                    3                    3                    3   
E                 test                 test                 test   
F                  foo                  foo                  foo   

                     3  
A                   12  
B  2019-10-01 00:00:00  
C                    1  
D                    3  
E                 test  
F                  foo

In [91]:
df2.sort_index(axis=0,ascending=False)

A          B    C  D     E    F
3  12 2019-10-01  1.0  3  test  foo
2  12 2019-10-01  1.0  3  test  foo
1  12 2019-10-01  1.0  3  test  foo
0  12 2019-10-01  1.0  3  test  foo

In [92]:
df2.sort_values(by='E')

A          B    C  D     E    F
0  12 2019-10-01  1.0  3  test  foo
1  12 2019-10-01  1.0  3  test  foo
2  12 2019-10-01  1.0  3  test  foo
3  12 2019-10-01  1.0  3  test  foo

# pandas选择数据

In [94]:
import numpy as np

In [95]:
import pandas as pd

In [96]:
dates=pd.date_range('20191002',periods=6)

In [99]:
df=pd.DataFrame(np.arange(24).reshape((6,4)),index=dates,columns=['A','B','C','D'])

In [100]:
df

A   B   C   D
2019-10-02   0   1   2   3
2019-10-03   4   5   6   7
2019-10-04   8   9  10  11
2019-10-05  12  13  14  15
2019-10-06  16  17  18  19
2019-10-07  20  21  22  23

In [101]:
print(df['A'])

2019-10-02     0
2019-10-03     4
2019-10-04     8
2019-10-05    12
2019-10-06    16
2019-10-07    20
Freq: D, Name: A, dtype: int32


In [102]:
print(df.A)

2019-10-02     0
2019-10-03     4
2019-10-04     8
2019-10-05    12
2019-10-06    16
2019-10-07    20
Freq: D, Name: A, dtype: int32


In [103]:
print(df[0:3])

            A  B   C   D
2019-10-02  0  1   2   3
2019-10-03  4  5   6   7
2019-10-04  8  9  10  11


In [104]:
print(df['20191002':'20191005'])

             A   B   C   D
2019-10-02   0   1   2   3
2019-10-03   4   5   6   7
2019-10-04   8   9  10  11
2019-10-05  12  13  14  15


### select by label:loc  通过标签选择数据

In [105]:
print(df.loc['20191003'])

A    4
B    5
C    6
D    7
Name: 2019-10-03 00:00:00, dtype: int32


In [106]:
print(df.loc[:,['A','B']])

             A   B
2019-10-02   0   1
2019-10-03   4   5
2019-10-04   8   9
2019-10-05  12  13
2019-10-06  16  17
2019-10-07  20  21


In [107]:
print(df.loc['20191003',['A','B']])

A    4
B    5
Name: 2019-10-03 00:00:00, dtype: int32


### select by position:iloc  通过序号选择数据

In [108]:
print(df.iloc[3])

A    12
B    13
C    14
D    15
Name: 2019-10-05 00:00:00, dtype: int32


In [109]:
print(df.iloc[3,2])

14


In [112]:
print(df.iloc[2:4,1:3])

             B   C
2019-10-04   9  10
2019-10-05  13  14


### Boolean indexing

In [113]:
df

A   B   C   D
2019-10-02   0   1   2   3
2019-10-03   4   5   6   7
2019-10-04   8   9  10  11
2019-10-05  12  13  14  15
2019-10-06  16  17  18  19
2019-10-07  20  21  22  23

In [114]:
print(df[df.A>8])

             A   B   C   D
2019-10-05  12  13  14  15
2019-10-06  16  17  18  19
2019-10-07  20  21  22  23


In [115]:
print(df.A>9)

2019-10-02    False
2019-10-03    False
2019-10-04    False
2019-10-05     True
2019-10-06     True
2019-10-07     True
Freq: D, Name: A, dtype: bool


# pandas设置值

In [187]:
import numpy as np

In [188]:
import pandas as pd

In [189]:
dates=pd.date_range('20191001',periods=6)

In [190]:
dates

DatetimeIndex(['2019-10-01', '2019-10-02', '2019-10-03', '2019-10-04',
               '2019-10-05', '2019-10-06'],
              dtype='datetime64[ns]', freq='D')

In [212]:
df=pd.DataFrame(np.arange(36).reshape((6,6)),columns=dates,index=['A','B','C','D','E','F'])

In [213]:
df

2019-10-01  2019-10-02  2019-10-03  2019-10-04  2019-10-05  2019-10-06
A           0           1           2           3           4           5
B           6           7           8           9          10          11
C          12          13          14          15          16          17
D          18          19          20          21          22          23
E          24          25          26          27          28          29
F          30          31          32          33          34          35

In [214]:
print(df.iloc[2,3])

15


In [215]:
df.iloc[2,3]=23

In [216]:
df

2019-10-01  2019-10-02  2019-10-03  2019-10-04  2019-10-05  2019-10-06
A           0           1           2           3           4           5
B           6           7           8           9          10          11
C          12          13          14          23          16          17
D          18          19          20          21          22          23
E          24          25          26          27          28          29
F          30          31          32          33          34          35

In [217]:
df.loc['D','20191003']=377    # 【行，列】

In [218]:
df

2019-10-01  2019-10-02  2019-10-03  2019-10-04  2019-10-05  2019-10-06
A           0           1           2           3           4           5
B           6           7           8           9          10          11
C          12          13          14          23          16          17
D          18          19         377          21          22          23
E          24          25          26          27          28          29
F          30          31          32          33          34          35

In [219]:
df['2019-10-07']=6

In [220]:
df

2019-10-01 00:00:00  2019-10-02 00:00:00  2019-10-03 00:00:00  \
A                    0                    1                    2   
B                    6                    7                    8   
C                   12                   13                   14   
D                   18                   19                  377   
E                   24                   25                   26   
F                   30                   31                   32   

   2019-10-04 00:00:00  2019-10-05 00:00:00  2019-10-06 00:00:00  2019-10-07  
A                    3                    4                    5           6  
B                    9                   10                   11           6  
C                   23                   16                   17           6  
D                   21                   22                   23           6  
E                   27                   28                   29           6  
F                   33                   34                   35           6

In [224]:
df=df.transpose()

In [225]:
df['G']=9   # 只能对列操作

In [227]:
df=df.transpose()

In [228]:
df

2019-10-01 00:00:00  2019-10-02 00:00:00  2019-10-03 00:00:00  \
A                    0                    1                    2   
B                    6                    7                    8   
C                   12                   13                   14   
D                   18                   19                  377   
E                   24                   25                   26   
F                   30                   31                   32   
G                    9                    9                    9   

   2019-10-04 00:00:00  2019-10-05 00:00:00  2019-10-06 00:00:00  2019-10-07  
A                    3                    4                    5           6  
B                    9                   10                   11           6  
C                   23                   16                   17           6  
D                   21                   22                   23           6  
E                   27                   28                   29           6  
F                   33                   34                   35           6  
G                    9                    9                    9           9

# pandas处理丢失数据

In [230]:
import numpy as np

In [231]:
import pandas as pd

In [232]:
dates=pd.date_range('20130101',periods=6)

In [234]:
df=pd.DataFrame(np.arange(24).reshape((6,4)),index=dates,columns=['A','B','C','D'])

In [238]:
df

A     B     C   D
2013-01-01   0   NaN   2.0   3
2013-01-02   4   5.0   NaN   7
2013-01-03   8   9.0  10.0  11
2013-01-04  12  13.0  14.0  15
2013-01-05  16  17.0  18.0  19
2013-01-06  20  21.0  22.0  23

In [235]:
df.iloc[0,1]=np.nan

In [236]:
df.iloc[1,2]=np.nan

In [239]:
print(df.dropna(axis=0,how='any'))  # how=['any','all']  丢掉包含NAN数据的行或列

             A     B     C   D
2013-01-03   8   9.0  10.0  11
2013-01-04  12  13.0  14.0  15
2013-01-05  16  17.0  18.0  19
2013-01-06  20  21.0  22.0  23


In [240]:
  print(df.fillna(value=0))    # 填补NAN处的值

             A     B     C   D
2013-01-01   0   0.0   2.0   3
2013-01-02   4   5.0   0.0   7
2013-01-03   8   9.0  10.0  11
2013-01-04  12  13.0  14.0  15
2013-01-05  16  17.0  18.0  19
2013-01-06  20  21.0  22.0  23


In [243]:
print(np.any(df.isnull()==True))    # 检查是否有缺失数据

True


# pandas导入导出数据

In [1]:
import numpy as np

In [2]:
import pandas as pd

#### read_csv、read_excel、read_hdf、read_sql、read_json、read_html、read_clipboard

#### to_csv、to_excel、to_hdf、to_sql、to_json、to_html、to_clipboard

In [3]:
data=pd.read_csv('F:/doc/ID.csv')  

In [4]:
print(data)

    student ID     name  age  gender
0         1100     ally   21  Female
1         1101      kel   22    Male
2         1102     keil   22    Male
3         1103      bow   22  Female
4         1104     rita   24    Male
5         1105     tony   23  Female
6         1106  aldrich   21    Male
7         1107      tim   34  Female
8         1108     timi   32    Male
9         1109    right   33    Male
10        1110     kimi   31  Female
11        1111     jole   30  Female
12        1112    david   26    Male
13        1113    catty   27    Male
14        1114   hamile   37  Female
15        1115    tilli   24  Female
16        1116    peter   19    Male
17        1117   flower   19  Female
18        1118      sky   23    Male
19        1119    sugar   38  Female
20        1120    sweat   33    Male
21        1121    candy   31    Male


In [7]:
data.to_pickle('student.pickle')  #导出文件至默认路径 

# 合并concat   (concatenating)

In [8]:
import pandas as pd

In [9]:
import numpy as np

In [10]:
df1=pd.DataFrame(np.ones((3,4))*0,columns=['a','b','c','d'])

In [11]:
df2=pd.DataFrame(np.ones((3,4))*1,columns=['a','b','c','d'])

In [12]:
df3=pd.DataFrame(np.ones((3,4))*2,columns=['a','b','c','d'])

In [13]:
print(df1)

     a    b    c    d
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0


In [14]:
print(df2)

     a    b    c    d
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0


In [15]:
print(df3)

     a    b    c    d
0  2.0  2.0  2.0  2.0
1  2.0  2.0  2.0  2.0
2  2.0  2.0  2.0  2.0


In [16]:
result=pd.concat([df1,df2,df3],axis=0)

In [17]:
print(result)

     a    b    c    d
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0
0  2.0  2.0  2.0  2.0
1  2.0  2.0  2.0  2.0
2  2.0  2.0  2.0  2.0


In [20]:
result1=pd.concat([df1,df2,df3],axis=0,ignore_index=True)

In [21]:
print(result1)

     a    b    c    d
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
3  1.0  1.0  1.0  1.0
4  1.0  1.0  1.0  1.0
5  1.0  1.0  1.0  1.0
6  2.0  2.0  2.0  2.0
7  2.0  2.0  2.0  2.0
8  2.0  2.0  2.0  2.0


In [25]:
df1=pd.DataFrame(np.ones((3,4))*0,columns=['a','b','c','d'],index=[1,2,3])

In [27]:
df2=pd.DataFrame(np.ones((3,4))*1,columns=['b','c','d','e'],index=[2,3,4])

In [28]:
print(df1)

     a    b    c    d
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0


In [29]:
print(df2)

     b    c    d    e
2  1.0  1.0  1.0  1.0
3  1.0  1.0  1.0  1.0
4  1.0  1.0  1.0  1.0


In [30]:
res=pd.concat([df1,df2])

e:\python\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


In [31]:
print(res)

     a    b    c    d    e
1  0.0  0.0  0.0  0.0  NaN
2  0.0  0.0  0.0  0.0  NaN
3  0.0  0.0  0.0  0.0  NaN
2  NaN  1.0  1.0  1.0  1.0
3  NaN  1.0  1.0  1.0  1.0
4  NaN  1.0  1.0  1.0  1.0


In [35]:
res=pd.concat([df1,df2],join='outer',sort=False)   #默认join=outer

In [36]:
print(res)

     a    b    c    d    e
1  0.0  0.0  0.0  0.0  NaN
2  0.0  0.0  0.0  0.0  NaN
3  0.0  0.0  0.0  0.0  NaN
2  NaN  1.0  1.0  1.0  1.0
3  NaN  1.0  1.0  1.0  1.0
4  NaN  1.0  1.0  1.0  1.0


In [39]:
res=pd.concat([df1,df2],join='inner',sort=False,ignore_index=True)   #交集

In [40]:
print(res)

     b    c    d
0  0.0  0.0  0.0
1  0.0  0.0  0.0
2  0.0  0.0  0.0
3  1.0  1.0  1.0
4  1.0  1.0  1.0
5  1.0  1.0  1.0


In [46]:
res=pd.concat([df1,df2],axis=1,sort=False,join_axes=[df1.index])

e:\python\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: The join_axes-keyword is deprecated. Use .reindex or .reindex_like on the result to achieve the same functionality.
  """Entry point for launching an IPython kernel.


In [47]:
print(res)

     a    b    c    d    b    c    d    e
1  0.0  0.0  0.0  0.0  NaN  NaN  NaN  NaN
2  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0
3  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0


In [50]:
res=df1.append(df2,ignore_index=True,sort=True)

In [51]:
print(res)

     a    b    c    d    e
0  0.0  0.0  0.0  0.0  NaN
1  0.0  0.0  0.0  0.0  NaN
2  0.0  0.0  0.0  0.0  NaN
3  NaN  1.0  1.0  1.0  1.0
4  NaN  1.0  1.0  1.0  1.0
5  NaN  1.0  1.0  1.0  1.0


# pandas合并merge

In [52]:
import numpy as np

In [53]:
import pandas as pd

In [55]:
df=pd.DataFrame(np.arange(12).reshape((3,4)))
print(df)

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11


In [56]:
df.mean()

0    4.0
1    5.0
2    6.0
3    7.0
dtype: float64

In [57]:
df.describe()

0    1     2     3
count  3.0  3.0   3.0   3.0
mean   4.0  5.0   6.0   7.0
std    4.0  4.0   4.0   4.0
min    0.0  1.0   2.0   3.0
25%    2.0  3.0   4.0   5.0
50%    4.0  5.0   6.0   7.0
75%    6.0  7.0   8.0   9.0
max    8.0  9.0  10.0  11.0